[tasks]
dev = { run = "flutter run", description = "Run mobile app" }
build = { run = "flutter build", description = "Build mobile app" }
install = { run = "flutter pub get", description = "Install dependencies", sources = ["pubspec.yaml", "pubspec.lock"] }
lint = { run = "flutter analyze", description = "Analyze mobile app" }
format = { run = "dart format .", description = "Format mobile app" }
test = { run = "flutter test", description = "Test mobile app" }
"gen:l10n" = { run = "flutter gen-l10n", description = "Generate localizations" }
"gen:api" = { run = "dart run swagger_parser", description = "Generate API client from OpenAPI" }
