name: mobile
description: Flutter mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0
  flutter: ^3.38.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  
  # State Management
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.1
  
  # Routing
  go_router: ^17.0.1
  
  # Network
  dio: ^5.8.0
  retrofit: ^4.5.0
  
  # Models
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  
  # DI
  get_it: ^8.0.3
  injectable: ^2.6.0
  
  # Utils
  jiffy: ^6.3.2
  
  # Firebase
  firebase_core: ^3.14.0
  firebase_crashlytics: ^4.3.7
  
  # UI
  cupertino_icons: ^1.0.8
  forui: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
  
  # Code Generation
  build_runner: ^2.4.15
  freezed: ^3.0.0
  json_serializable: ^6.9.4
  retrofit_generator: ^10.2.1
  riverpod_generator: ^3.0.3
  injectable_generator: ^2.7.0
  
  # Testing
  mocktail: ^1.0.4
  
  # API Generation
  swagger_parser: ^1.3.0

flutter:
  generate: true
  uses-material-design: true
