name: mobile
description: Flutter mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0
  flutter: ^3.38.0

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0
  firebase_core: ^3.14.0
  firebase_crashlytics: ^4.3.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  forui: ^0.17.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^17.0.1
  injectable: ^2.6.0
  intl: any
  jiffy: ^6.3.2
  json_annotation: ^4.9.0
  retrofit: ^4.5.0
  riverpod_annotation: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  retrofit_generator: ^10.2.1
  riverpod_generator: ^3.0.3
  swagger_parser: ^1.3.0
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
